apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: DS_PROMETHEUS
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: POST
      orgId: 1

  - name: VictoriaMetrics
    type: prometheus
    uid: DS_VICTORIAMETRICS
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 1s
      httpMethod: POST
      orgId: 1
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      customQueryParameters: ''
