---
- name: Allow metrics port (Debian)
  ufw:
    rule: allow
    port: "{{ ffrtmp_worker_metrics_port }}"
    proto: tcp
  when: ansible_os_family == 'Debian'

- name: Allow metrics port (RedHat)
  firewalld:
    port: "{{ ffrtmp_worker_metrics_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == 'RedHat'
